[package]
name = "kslot_map"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

[features]
default = ["linked_list_slot_map"]
linked_list_slot_map = []

[dependencies]
serde = { version = "1.0.193", default-features = false, features=["serde_derive"], optional = true }
